version: "3.7"
services:
  web:
    build: ./web
    depends_on:
      - api
    env_file:
      - ./web/.env.docker
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app:delegated
  api:
    build: ./api
    hostname: api
    env_file:
      - ./api/.env.docker
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app:delegated
    depends_on:
      - db
  db:
    # https://hub.docker.com/_/postgres
    image: postgres
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: epr
      POSTGRES_PASSWORD: epr
      POSTGRES_DATABASE: epr