version: "3.7"
services:
  api-dev:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    env_file:
      - ./api/.env.docker
    volumes:
      - ./api:/app:delegated
  web-dev:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    env_file:
      - ./web/.env.docker
    volumes:
      - ./web:/app:delegated
    hostname: api
  db:
    # https://hub.docker.com/_/postgres
    image: postgres
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: epr
      POSTGRES_PASSWORD: epr
      POSTGRES_DATABASE: epr
