# https://github.com/peter-evans/slash-command-dispatch
# https://github.com/peter-evans/slash-command-dispatch/blob/master/docs/getting-started.md
#
name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    name: Slash Command Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commands: example
          repository: bcgov/epr
